version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REACT_APP_DROID_HOST=127.0.0.1
    volumes:
      - data:/app/data
      - auth:/app/backend/auth
    restart: always
volumes:
   data:
   auth: